// SQL only. Lifecycle rules live in devices/registry.js.
const FULL = `id, serial, batch_id, hardware_rev, secret_enc, secret_prev_enc, secret_prev_expires_at,
  claim_code_hash, status, status_reason, disabled_by, family_id, child_id, firmware_version,
  last_seen_at, claimed_at, created_at, updated_at`;

const PUBLIC = `id, serial, batch_id, hardware_rev, status, status_reason, disabled_by, family_id, child_id,
  firmware_version, last_seen_at, claimed_at, created_at, updated_at`;

// The parent-facing reads carry the toy's profile. Columns are qualified
// because devices and buddy_profiles share created_at and updated_at.
const WITH_PROFILE = `${PUBLIC.split(",").map((c) => `d.${c.trim()}`).join(", ")},
  p.name AS profile_name, p.role AS profile_role, p.personality AS profile_personality, p.personality_source AS profile_source`;
const FROM_WITH_PROFILE = "devices d LEFT JOIN buddy_profiles p ON p.device_id = d.id";

const INSERT_CHUNK = 500;

export async function insertBatch(db, { label, hardwareRev, size, notes = null }) {
  const r = await db.query(
    `INSERT INTO device_batches (label, hardware_rev, size, notes) VALUES ($1, $2, $3, $4)
     RETURNING id, label, hardware_rev, size, notes, created_at`,
    [label, hardwareRev, size, notes],
  );
  return r.rows[0];
}

export async function findBatchByLabel(db, label) {
  const r = await db.query('SELECT id, label, hardware_rev, size, notes, created_at FROM device_batches WHERE label = $1', [label]);
  return r.rows[0] ?? null;
}

// Ids are generated by the caller because the secret is sealed with the id
// as associated data before the row exists.
export async function insertDevices(db, rows) {
  for (let start = 0; start < rows.length; start += INSERT_CHUNK) {
    const chunk = rows.slice(start, start + INSERT_CHUNK);
    const params = [];
    const values = chunk.map((row, i) => {
      params.push(row.id, row.serial, row.batchId, row.hardwareRev, row.secretEnc, row.claimCodeHash);
      const b = i * 6;
      return `($${b + 1}, $${b + 2}, $${b + 3}, $${b + 4}, $${b + 5}, $${b + 6})`;
    });
    await db.query(
      `INSERT INTO devices (id, serial, batch_id, hardware_rev, secret_enc, claim_code_hash) VALUES ${values.join(', ')}`,
      params,
    );
  }
}

export async function findById(db, id) {
  const r = await db.query(`SELECT ${FULL} FROM devices WHERE id = $1`, [id]);
  return r.rows[0] ?? null;
}

export async function findByIdForUpdate(tx, id) {
  const r = await tx.query(`SELECT ${FULL} FROM devices WHERE id = $1 FOR UPDATE`, [id]);
  return r.rows[0] ?? null;
}

export async function findInFamilyForUpdate(tx, id, familyId) {
  const r = await tx.query(`SELECT ${FULL} FROM devices WHERE id = $1 AND family_id = $2 FOR UPDATE`, [id, familyId]);
  return r.rows[0] ?? null;
}

export async function findInFamily(db, id, familyId) {
  const r = await db.query(`SELECT ${WITH_PROFILE} FROM ${FROM_WITH_PROFILE} WHERE d.id = $1 AND d.family_id = $2`, [id, familyId]);
  return r.rows[0] ?? null;
}

// Two parents racing on one code serialize here; the loser sees the row
// already active and gets the same 404 as a wrong code.
export async function findByClaimHashForUpdate(tx, hash) {
  const r = await tx.query(`SELECT ${FULL} FROM devices WHERE claim_code_hash = $1 FOR UPDATE`, [hash]);
  return r.rows[0] ?? null;
}

export async function listByFamily(db, familyId) {
  const r = await db.query(
    `SELECT ${WITH_PROFILE} FROM ${FROM_WITH_PROFILE} WHERE d.family_id = $1 ORDER BY d.claimed_at, d.id`,
    [familyId],
  );
  return r.rows;
}

export async function claim(tx, id, { familyId, childId = null }) {
  const r = await tx.query(
    `UPDATE devices SET family_id = $2, child_id = $3, status = 'active', claimed_at = now(),
       status_reason = NULL, disabled_by = NULL, updated_at = now()
     WHERE id = $1 AND status = 'provisioned' RETURNING ${PUBLIC}`,
    [id, familyId, childId],
  );
  return r.rows[0] ?? null;
}

export async function setStatus(db, id, { status, statusReason = null, disabledBy = null }) {
  const r = await db.query(
    `UPDATE devices SET status = $2, status_reason = $3, disabled_by = $4, updated_at = now()
     WHERE id = $1 RETURNING ${PUBLIC}`,
    [id, status, statusReason, disabledBy],
  );
  return r.rows[0] ?? null;
}

export async function unpair(db, id) {
  const r = await db.query(
    `UPDATE devices SET family_id = NULL, child_id = NULL, status = 'provisioned', claimed_at = NULL,
       status_reason = NULL, disabled_by = NULL, updated_at = now()
     WHERE id = $1 RETURNING ${PUBLIC}`,
    [id],
  );
  return r.rows[0] ?? null;
}

export async function setChild(db, id, childId) {
  const r = await db.query(
    `UPDATE devices SET child_id = $2, updated_at = now() WHERE id = $1 RETURNING ${PUBLIC}`,
    [id, childId],
  );
  return r.rows[0] ?? null;
}

export async function setClaimHash(db, id, hash) {
  await db.query('UPDATE devices SET claim_code_hash = $2, updated_at = now() WHERE id = $1', [id, hash]);
}

export async function setSecrets(db, id, { secretEnc, secretPrevEnc, secretPrevExpiresAt }) {
  await db.query(
    `UPDATE devices SET secret_enc = $2, secret_prev_enc = $3, secret_prev_expires_at = $4, updated_at = now()
     WHERE id = $1`,
    [id, secretEnc, secretPrevEnc, secretPrevExpiresAt],
  );
}

export async function touchSeen(db, id, firmwareVersion = null) {
  await db.query(
    `UPDATE devices SET last_seen_at = now(), firmware_version = COALESCE($2, firmware_version) WHERE id = $1`,
    [id, firmwareVersion],
  );
}

export async function listBatches(db) {
  const r = await db.query(`
    SELECT b.id, b.label, b.hardware_rev, b.size, b.notes, b.created_at,
           count(d.id)::int AS device_count,
           count(d.id) FILTER (WHERE d.status = 'active')::int AS active_count
    FROM device_batches b LEFT JOIN devices d ON d.batch_id = b.id
    GROUP BY b.id ORDER BY b.created_at DESC, b.label`);
  return r.rows;
}

export async function listDevices(db, { status = null, batchId = null, familyId = null, limit = 50, offset = 0 }) {
  const r = await db.query(
    `SELECT ${PUBLIC} FROM devices
     WHERE ($1::text IS NULL OR status = $1)
       AND ($2::uuid IS NULL OR batch_id = $2)
       AND ($3::uuid IS NULL OR family_id = $3)
     ORDER BY created_at, serial LIMIT $4 OFFSET $5`,
    [status, batchId, familyId, limit, offset],
  );
  return r.rows;
}

export async function insertEvent(db, { deviceId, event, actorKind, actorId = null, detail = null }) {
  await db.query(
    'INSERT INTO device_events (device_id, event, actor_kind, actor_id, detail) VALUES ($1, $2, $3, $4, $5)',
    [deviceId, event, actorKind, actorId, detail],
  );
}

export async function insertEventsForBatch(db, batchId, { event, actorKind, actorId = null }) {
  await db.query(
    `INSERT INTO device_events (device_id, event, actor_kind, actor_id)
     SELECT id, $2, $3, $4 FROM devices WHERE batch_id = $1`,
    [batchId, event, actorKind, actorId],
  );
}

export async function listEvents(db, deviceId) {
  const r = await db.query(
    'SELECT id, event, actor_kind, actor_id, detail, at FROM device_events WHERE device_id = $1 ORDER BY at, id',
    [deviceId],
  );
  return r.rows;
}

// What parents and admins see. Never a secret, never a claim code.
export function toDto(row) {
  return {
    id: row.id,
    serial: row.serial,
    hardware_rev: row.hardware_rev,
    status: row.status,
    status_reason: row.status_reason,
    disabled_by: row.disabled_by,
    child_id: row.child_id,
    firmware_version: row.firmware_version,
    last_seen_at: row.last_seen_at,
    claimed_at: row.claimed_at,
    created_at: row.created_at,
    // null on rows read without the join (admin lists, status updates).
    profile: row.profile_name ? {
      name: row.profile_name,
      role: row.profile_role,
      personality: row.profile_personality,
      personality_source: row.profile_source,
    } : null,
  };
}
